on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: az204repo.azurecr.io
        username: ${{ secrets.acr_az204repo_username }}
        password: ${{ secrets.acr_az204repo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/nodeapp" -f  "Dockerfile" -t az204repo.azurecr.io/kubecluster:${{ github.sha }}
        docker push az204repo.azurecr.io/kubecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubecluster30f1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubecluster30f1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubecluster30f1
        container-registry-url: az204repo.azurecr.io
        container-registry-username: ${{ secrets.acr_az204repo_username }}
        container-registry-password: ${{ secrets.acr_az204repo_password }}
        secret-name: kubeclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kubecluster30f1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          az204repo.azurecr.io/kubecluster:${{ github.sha }}
        imagepullsecrets: |
          kubeclusterdockerauth